on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  Windows:
    name: build-linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Execute one line
      run: cd build
    - name: executing make file
      run: make all
    - name: executing test cases
      run: ./test/Calculator_tst
      
