on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  Windows:
    name: build-linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Execute one line
      run: pwd
