on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  Windows:
    name: build-linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Execute one line
      run: pwd
    - name: list files
      run: ls
    - name: run make file
      run: cd Calculator/build && make all
    - name: executing test cases
      run: ./Calculator/build/test/Calculator_tst
  
      
